### ISSUE TITLE
float buying values issue

### ISSUE THREAD

**Issue by SkullCandby** [bilix-software/pump-fun-token-launcher#1]
You soft works brilliant except for one part. For some reason when I am trying to use float values to buy a token it does not launch, but it still says that it launched successfully and generates pump.fun and jito links

**Comment by bilix-software** [comment]
I have also tested it with float values so I assume the reason why its failing must be different. It currently sents to jito and receives a bundle hash which is output to the UI. If it fails that reason is not sent back to the user currently. But I can see it in the backend. If you tell me which token you were trying to launch I can have a look at the logs for you and tell you why it failed. (You can also do this through email or telegram if you don't want this info to be public).

**Comment by SkullCandby** [comment]
I think I`ll hit you up later. Also, people are saying that bundles don`t work anymore. Do you if it`s possible to fix and how much time will it take?

**Comment by bilix-software** [comment]
I just tested it through viper.bot, no issues with deploying: https://pump.fun/3VN9SdXkgZpzCPaJ2MpcxPpSujbUxP8mJ7meSV6upump
